# Generated by Django 2.2.7 on 2026-07-31 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191122_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/visitor_photos'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 31, 6, 45, 14, 719549)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 7, 31, 6, 45, 14, 719561)),
        ),
    ]
