# Generated by Django 2.2.7 on 2026-07-31 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20260731_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 31, 6, 55, 6, 653207)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 7, 31, 6, 55, 6, 653218)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/visitor_photos/'),
        ),
    ]
