# Generated by Django 5.2.16 on 2026-08-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20260731_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='meeting',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 3, 15, 38, 24, 60464)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 8, 3, 15, 38, 24, 60497)),
        ),
    ]
