# Generated by Django 5.2.16 on 2026-08-03 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_meeting_aadhaar_number_meeting_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 3, 15, 40, 39, 97155)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2026, 8, 3, 15, 40, 39, 97187)),
        ),
    ]
